server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menudb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gangnam
    password: gangnam

mybatis:
  mapper-location: mapper/*.xml